const cfg=window.CONTENT_BANK_CONFIG,db=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);let ideas=[],filter='全部',editing=null;const $=id=>document.getElementById(id),safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function view(session){$('auth').classList.toggle('hidden',!!session);$('app').classList.toggle('authed',!!session);if(session)load()}
function render(){let q=$('search').value.trim(),rows=ideas.filter(x=>(filter==='全部'||x.type===filter)&&(!q||x.title.includes(q)||(x.tags||[]).join('').includes(q)));$('ideaCount').textContent=$('totalCount').textContent=ideas.length;$('pendingCount').textContent=ideas.filter(x=>x.status==='待加工').length;$('workingCount').textContent=ideas.filter(x=>x.status==='加工中').length;$('confirmedCount').textContent=ideas.filter(x=>x.status==='已确认').length;$('list').innerHTML=rows.length?rows.map((x,i)=>`<div class="row"><div class="idx">${String(i+1).padStart(2,'0')}</div><div><strong>${safe(x.title)}</strong><div class="tags">${(x.tags||[]).map(t=>'#'+safe(t)).join('　')}</div></div><div class="muted">${safe(x.type)}</div><div class="row-actions"><button onclick="editIdea('${x.id}')">编辑</button><button onclick="removeIdea('${x.id}')">删除</button></div></div>`).join(''):'<div class="empty">暂无素材，点击“录入灵感”建立第一条资产</div>'}
async function load(){let {data,error}=await db.from('ideas').select('*').order('created_at',{ascending:false});if(error){$('list').innerHTML=`<div class="empty">读取失败：${safe(error.message)}</div>`;return}ideas=data||[];render()}
async function auth(mode){$('authError').textContent='';let args={email:$('email').value.trim(),password:$('password').value},r=mode==='signup'?await db.auth.signUp(args):await db.auth.signInWithPassword(args);if(r.error)$('authError').textContent=r.error.message;else if(mode==='signup'&&!r.data.session)$('authError').textContent='账号已创建，请到邮箱完成确认后登录。'}
function openForm(x={}){editing=x.id||null;$('formTitle').textContent=editing?'编辑灵感':'录入灵感';$('ideaTitle').value=x.title||'';$('ideaType').value=x.type||'世界底层规则';$('ideaTags').value=(x.tags||[]).join(',');$('ideaStatus').value=x.status||'待加工';$('ideaContent').value=x.content||'';$('formError').textContent='';$('modal').classList.add('open')}
window.editIdea=id=>openForm(ideas.find(x=>x.id===id));window.removeIdea=async id=>{if(!confirm('确定删除这条素材吗？'))return;let {error}=await db.from('ideas').delete().eq('id',id);error?alert(error.message):load()};
$('ideaForm').onsubmit=async e=>{e.preventDefault();let p={title:$('ideaTitle').value.trim(),type:$('ideaType').value,tags:$('ideaTags').value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),status:$('ideaStatus').value,content:$('ideaContent').value.trim()},r=editing?await db.from('ideas').update(p).eq('id',editing):await db.from('ideas').insert(p);if(r.error)$('formError').textContent=r.error.message;else{$('modal').classList.remove('open');load()}};
$('login').onclick=()=>auth('login');$('signup').onclick=()=>auth('signup');$('logout').onclick=()=>db.auth.signOut();$('add').onclick=()=>openForm();$('close').onclick=()=>$('modal').classList.remove('open');$('search').oninput=render;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.textContent;render()});db.auth.getSession().then(({data})=>view(data.session));db.auth.onAuthStateChange((_e,s)=>view(s));
