const cfg=window.CONTENT_BANK_CONFIG,db=supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);let ideas=[],assets=[],filter='全部',editing=null,assetEditing=null,currentView='ideas';const $=id=>document.getElementById(id),safe=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const grid=document.querySelector('.grid'),rawGrid=grid.innerHTML,nav=[...document.querySelectorAll('.nav button')];nav[0].dataset.view='ideas';nav[1].dataset.view='ideas';nav[2].dataset.view='assets';nav[2].querySelector('em').id='assetCount';
document.body.insertAdjacentHTML('beforeend',`<div class="modal-wrap" id="assetModal"><form class="modal" id="assetForm"><div class="modal-head"><h2 id="assetFormTitle">加工资产卡</h2><button type="button" class="close" id="assetClose">×</button></div><select class="field" id="assetType"><option>规则卡</option><option>人物卡</option><option>情节卡</option><option>场景卡</option></select><input class="field" id="assetTitle" required placeholder="资产名称"><input class="field" id="assetTags" placeholder="标签，用逗号分隔"><textarea class="field" id="assetSummary" placeholder="一句话摘要：这张卡最核心的价值"></textarea><textarea class="field" id="assetContent" placeholder="完整设定：目标、限制、冲突、代价、触发条件、可复用方式……"></textarea><select class="field" id="assetStatus"><option>草稿</option><option>待确认</option><option>已确认</option></select><button class="btn" type="submit">保存资产卡</button><div class="error" id="assetError"></div></form></div>`);
function view(session){$('auth').classList.toggle('hidden',!!session);$('app').classList.toggle('authed',!!session);if(session)loadAll()}
async function loadAll(){let [ir,ar]=await Promise.all([db.from('ideas').select('*').order('created_at',{ascending:false}),db.from('assets').select('*').order('created_at',{ascending:false})]);if(ir.error||ar.error){$('list').innerHTML=`<div class="empty">读取失败：${safe((ir.error||ar.error).message)}</div>`;return}ideas=ir.data||[];assets=ar.data||[];renderCurrent()}
function counts(){$('ideaCount').textContent=ideas.length;$('assetCount').textContent=assets.length;$('totalCount').textContent=ideas.length+assets.length;$('pendingCount').textContent=ideas.filter(x=>x.status==='待加工').length;$('workingCount').textContent=ideas.filter(x=>x.status==='加工中').length;$('confirmedCount').textContent=ideas.filter(x=>x.status==='已确认').length+assets.filter(x=>x.status==='已确认').length}
function bindChips(){document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.textContent;renderCurrent()})}
function renderIdeas(){const q=$('search').value.trim(),rows=ideas.filter(x=>(filter==='全部'||x.type===filter)&&(!q||x.title.includes(q)||(x.tags||[]).join('').includes(q)));$('list').innerHTML=rows.length?rows.map((x,i)=>`<div class="row"><div class="idx">${String(i+1).padStart(2,'0')}</div><div><strong>${safe(x.title)}</strong><div class="tags">${(x.tags||[]).map(t=>'#'+safe(t)).join('　')}</div></div><div class="muted">${safe(x.type)}</div><div class="row-actions"><button onclick="processIdea('${x.id}')">加工</button><button onclick="editIdea('${x.id}')">编辑</button><button onclick="removeIdea('${x.id}')">删除</button></div></div>`).join(''):'<div class="empty">暂无素材，点击“录入灵感”建立第一条资产</div>'}
function assetsMarkup(){return `<article class="panel" style="grid-column:1/-1"><div class="eyebrow">STRUCTURED ASSETS</div><h2>半成品资产库</h2><div class="chips"><button class="chip active">全部</button><button class="chip">规则卡</button><button class="chip">人物卡</button><button class="chip">情节卡</button><button class="chip">场景卡</button></div><div id="assetList"></div></article>`}
function renderAssets(){if(!$('assetList'))grid.innerHTML=assetsMarkup();bindChips();const q=$('search').value.trim(),rows=assets.filter(x=>(filter==='全部'||x.asset_type===filter)&&(!q||x.title.includes(q)||(x.tags||[]).join('').includes(q)));$('assetList').innerHTML=rows.length?rows.map((x,i)=>`<div class="row"><div class="idx">${String(i+1).padStart(2,'0')}</div><div><strong>${safe(x.title)}</strong><div class="tags">${safe(x.summary||'暂无摘要')}</div></div><div class="muted">${safe(x.asset_type)} · ${safe(x.status)}</div><div class="row-actions"><button onclick="editAsset('${x.id}')">编辑</button><button onclick="removeAsset('${x.id}')">删除</button></div></div>`).join(''):'<div class="empty">暂无半成品资产。在灵感原料中点击“加工”，生成第一张资产卡。</div>'}
function renderCurrent(){counts();if(currentView==='assets')renderAssets();else{if(!$('list')){grid.innerHTML=rawGrid;bindChips()}renderIdeas()}}
function switchView(target){currentView=target;filter='全部';nav.forEach(b=>b.classList.toggle('active',b.dataset.view===target));document.querySelector('.top h1').textContent=target==='assets'?'半成品资产库':'总览';$('add').textContent=target==='assets'?'＋ 新建资产卡':'＋ 录入灵感';if(target==='assets')grid.innerHTML=assetsMarkup();else grid.innerHTML=rawGrid;bindChips();renderCurrent()}
async function auth(mode){$('authError').textContent='';let args={email:$('email').value.trim(),password:$('password').value},r=mode==='signup'?await db.auth.signUp(args):await db.auth.signInWithPassword(args);if(r.error)$('authError').textContent=r.error.message;else if(mode==='signup'&&!r.data.session)$('authError').textContent='账号已创建，请到邮箱完成确认后登录。'}
function openIdea(x={}){editing=x.id||null;$('formTitle').textContent=editing?'编辑灵感':'录入灵感';$('ideaTitle').value=x.title||'';$('ideaType').value=x.type||'世界底层规则';$('ideaTags').value=(x.tags||[]).join(',');$('ideaStatus').value=x.status||'待加工';$('ideaContent').value=x.content||'';$('formError').textContent='';$('modal').classList.add('open')}
function openAsset(x={},source=null){assetEditing=x.id||null;$('assetFormTitle').textContent=assetEditing?'编辑资产卡':'加工资产卡';$('assetType').value=x.asset_type||(source?.type==='人物种子'?'人物卡':source?.type==='副本机制'?'情节卡':'规则卡');$('assetTitle').value=x.title||source?.title||'';$('assetTags').value=(x.tags||source?.tags||[]).join(',');$('assetSummary').value=x.summary||source?.content||'';$('assetContent').value=x.content||'';$('assetStatus').value=x.status||'草稿';$('assetForm').dataset.source=source?.id||x.source_idea_id||'';$('assetError').textContent='';$('assetModal').classList.add('open')}
window.editIdea=id=>openIdea(ideas.find(x=>x.id===id));window.processIdea=id=>openAsset({},ideas.find(x=>x.id===id));window.removeIdea=async id=>{if(!confirm('确定删除这条灵感吗？'))return;let {error}=await db.from('ideas').delete().eq('id',id);error?alert(error.message):loadAll()};window.editAsset=id=>openAsset(assets.find(x=>x.id===id));window.removeAsset=async id=>{if(!confirm('确定删除这张资产卡吗？'))return;let {error}=await db.from('assets').delete().eq('id',id);error?alert(error.message):loadAll()};
$('ideaForm').onsubmit=async e=>{e.preventDefault();let p={title:$('ideaTitle').value.trim(),type:$('ideaType').value,tags:$('ideaTags').value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),status:$('ideaStatus').value,content:$('ideaContent').value.trim()},r=editing?await db.from('ideas').update(p).eq('id',editing):await db.from('ideas').insert(p);if(r.error)$('formError').textContent=r.error.message;else{$('modal').classList.remove('open');loadAll()}};
$('assetForm').onsubmit=async e=>{e.preventDefault();let p={asset_type:$('assetType').value,title:$('assetTitle').value.trim(),tags:$('assetTags').value.split(/[,，]/).map(x=>x.trim()).filter(Boolean),summary:$('assetSummary').value.trim(),content:$('assetContent').value.trim(),status:$('assetStatus').value,source_idea_id:$('assetForm').dataset.source||null},r=assetEditing?await db.from('assets').update(p).eq('id',assetEditing):await db.from('assets').insert(p);if(r.error)$('assetError').textContent=r.error.message;else{$('assetModal').classList.remove('open');loadAll()}};
$('login').onclick=()=>auth('login');$('signup').onclick=()=>auth('signup');$('logout').onclick=()=>db.auth.signOut();$('add').onclick=()=>currentView==='assets'?openAsset():openIdea();$('close').onclick=()=>$('modal').classList.remove('open');$('assetClose').onclick=()=>$('assetModal').classList.remove('open');$('search').oninput=renderCurrent;nav.filter(b=>b.dataset.view).forEach(b=>b.onclick=()=>switchView(b.dataset.view));bindChips();db.auth.getSession().then(({data})=>view(data.session));db.auth.onAuthStateChange((_e,s)=>view(s));
