create extension if not exists pgcrypto;
create table if not exists public.ideas(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,title text not null check(char_length(title) between 1 and 200),type text not null default '灵感原料',tags text[] not null default '{}',status text not null default '待加工',content text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.ideas enable row level security;
drop policy if exists owner_select on public.ideas;drop policy if exists owner_insert on public.ideas;drop policy if exists owner_update on public.ideas;drop policy if exists owner_delete on public.ideas;
create policy owner_select on public.ideas for select using(auth.uid()=user_id);create policy owner_insert on public.ideas for insert with check(auth.uid()=user_id);create policy owner_update on public.ideas for update using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy owner_delete on public.ideas for delete using(auth.uid()=user_id);
create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now();return new;end;$$;drop trigger if exists ideas_set_updated_at on public.ideas;create trigger ideas_set_updated_at before update on public.ideas for each row execute function public.set_updated_at();

create table if not exists public.assets(id uuid primary key default gen_random_uuid(),user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,source_idea_id uuid references public.ideas(id) on delete set null,asset_type text not null check(asset_type in('规则卡','人物卡','情节卡','场景卡')),title text not null check(char_length(title) between 1 and 200),tags text[] not null default '{}',summary text not null default '',content text not null default '',status text not null default '草稿',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.assets enable row level security;
drop policy if exists asset_owner_select on public.assets;drop policy if exists asset_owner_insert on public.assets;drop policy if exists asset_owner_update on public.assets;drop policy if exists asset_owner_delete on public.assets;
create policy asset_owner_select on public.assets for select using(auth.uid()=user_id);create policy asset_owner_insert on public.assets for insert with check(auth.uid()=user_id);create policy asset_owner_update on public.assets for update using(auth.uid()=user_id) with check(auth.uid()=user_id);create policy asset_owner_delete on public.assets for delete using(auth.uid()=user_id);
drop trigger if exists assets_set_updated_at on public.assets;create trigger assets_set_updated_at before update on public.assets for each row execute function public.set_updated_at();
