// v19：长篇任务自动分章续写，避免单次输出达到上限后在句中截断。
(function(){
  if(!window.ContinuationTools)return;
  const T=window.ContinuationTools,MAX_REPAIRS=12;
  async function freshTask(id){const {data,error}=await db.from('pipeline_runs').select('*').eq('id',id).single();if(error)throw error;return data}
  function storyRange(task){if(task?.pipeline_type!=='故事开发')return null;const range=T.rangeFromText(task.input_brief,task.name);return range&&range.length>1?range:null}
  function instruction(no,isLast,range){return `自动续写修复：只输出第${no}章完整正文，不要重写其他章节。\n必须以“# 第${no}章｜章节标题”单独起行；从完整场景开头写到完整章尾，不得在句中截断，不得用梗概代替。\n${isLast?`本章正文后补充“## ${range[0]}—${range.at(-1)}章连续性质检”，检查人物、规则、时间线、伏笔、道具和章间衔接。\n`:''}全文最后单独一行输出 [[REPORT_COMPLETE]]。`}
  async function invoke(id,mode){const {data,error}=await db.functions.invoke('execute-pipeline',{body:{pipeline_id:id,...(mode?{mode}: {})}});if(error||!data?.ok)throw new Error(data?.error||error?.message||'未知错误')}
  async function repair(id,originalReview){let task=await freshTask(id),range=storyRange(task);if(!range)return task;let assembled=task.output_draft||'',tries=0;while(!T.complete(assembled,range)&&tries<MAX_REPAIRS){const target=T.nextTarget(assembled,range,/\[\[REPORT_COMPLETE\]\]/.test(assembled));if(!target)break;const prep=await db.from('pipeline_runs').update({output_draft:assembled,output_complete:false,status:'执行中',review_notes:instruction(target,target===range.at(-1),range),last_error:''}).eq('id',id);if(prep.error)throw prep.error;await invoke(id,'revise');const part=await freshTask(id),blocks=T.merge(assembled,part.output_draft||'');if(!blocks.some(x=>x.chapter_no===target))throw new Error(`续写结果未识别到第${target}章标题`);assembled=T.compose(blocks,range,false);tries++}
    const done=T.complete(assembled,range),finalText=T.compose(T.parseBlocks(assembled),range,done),update={output_draft:finalText,output_complete:done,review_notes:originalReview||'',status:done?'待审核':'失败',last_error:done?'':`自动续写达到 ${MAX_REPAIRS} 次上限，章节仍不完整`,quality_report:{chapter_range:range,chapter_count:T.parseBlocks(finalText).length,auto_continuation:true,complete:done}};const saved=await db.from('pipeline_runs').update(update).eq('id',id);if(saved.error)throw saved.error;return{...task,...update}}
  async function run(id,mode){const task=pipelines.find(x=>x.id===id);if(!task)return;const originalReview=task.review_notes||'';await db.from('pipeline_runs').update({status:'执行中',last_error:''}).eq('id',id);try{await invoke(id,mode);const result=await repair(id,originalReview);await loadAll();alert(result.output_complete?'AI 已完成全部章节并通过结构完整性检查，请审核正文。':'AI 已返回结果，请审核。')}catch(error){await db.from('pipeline_runs').update({status:'失败',last_error:error.message||String(error),review_notes:originalReview}).eq('id',id);await loadAll();alert('AI 执行失败：'+(error.message||error))}}
  window.executePipelineAI=async id=>{const task=pipelines.find(x=>x.id===id);if(!task)return;return run(id,null)};
  window.revisePipelineAI=async id=>{const task=pipelines.find(x=>x.id===id);if(!task)return;if(!task.output_draft?.trim()||!task.review_notes?.trim()){alert('重做需要原执行结果和人工审核意见。');return}return run(id,'revise')};
})();
